# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
# name = "Announcements"
 # url = "#announcements"
 # weight = 1

 [[main]] 
  name = "About"
  url = "#about"
  weight = 2

[[main]]
  name = "Courses"
  url = "#projects"
  weight = 3

[[main]]
  name = "Student Work"
  url = "studentwork/"
  weight = 4

[[main]]
  name = "Grants"
  url = "grants/"
  weight = 5

[[main]]
  name = "Links"
  url = "links/"
  weight = 6

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 7

  [[main]]
  name = "Showcase Schedule"
  url = "schedule/"
  weight = 8

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
